spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/health_coach_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

ai:
  google:
    gemini:
      api-key: "AIzaSyDvwZBj_QN0EkuxdZko9IN8232iMBg8ECE"